version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "weekly"
    versioning-strategy: increase-if-necessary
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
