[workspace]
members = [
    "crates/*"
]
resolver = "2"

[workspace.package]
version = "0.1.0"
rust-version = "1.85.0"
edition = "2024"

[workspace.dependencies]
lib-api-router = { path = "crates/lib-api-router" }
lib-web = { path = "crates/lib-web" }
lib-web-router = { path = "crates/lib-web-router" }

axum = "~0.8.1"
camino = "~1.1.9"
itertools = "~0.14.0"
phf = "~0.11.3"
tokio = { version = "~1.43.0", features = ["full"] }
phf_codegen = "~0.11.3"
glob = "~0.3.2"
mime_guess = "~2.0.5"
flate2 = "~1.1.0"

[workspace.lints.clippy]
unwrap_used = "deny"
unsafe_code = "deny"
