[workspace]
members = [
    "crates/*"
]
resolver = "2"

[workspace.package]
version = "0.1.0"
rust-version = "1.83.0"

[workspace.dependencies]
lib-api-router = { path = "crates/lib-api-router" }
lib-web = { path = "crates/lib-web" }
lib-web-router = { path = "crates/lib-web-router" }

axum = "0.7.9"
camino = "1.1.9"
itertools = "0.13.0"
phf = "0.11.2"
tokio = { version = "1.42.0", features = ["full"] }
phf_codegen = "0.11.2"
glob = "0.3.1"
mime_guess = "2.0.5"
flate2 = "1.0.35"
