[package]
name = "lib-web-router"
edition = "2021"
publish = false
version.workspace = true
rust-version.workspace = true

[dependencies]
lib-web.workspace = true

axum.workspace = true

[lints]
workspace = true
