[package]
name = "server"
edition = "2021"
publish = false
version.workspace = true

[dependencies]
lib-api-router.workspace = true
lib-web-router.workspace = true

axum.workspace = true
tokio.workspace = true
