name: Lint Javascript
on:
  pull_request:
    paths:
      - '**/*.js'
      - '**/*.ts'
      - '**/*.json'
      - '**/*.vue'
      - '**/*.css'
      - '**/*.scss'
jobs:
  build-node:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'
      - name: Update Rust
        run: rustup update
      - name: Add Clippy
        run: rustup component add clippy
      - name: Build Rust project
        run: cargo build
      - name: ESLint.js check
        run: |
          cd crates/lib-web
          npm run lint