name: Test Project

on: [ pull_request ]

jobs:
  build-node:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'
      - name: Update Rust
        run: rustup update
      - name: Build Rust project
        run: cargo build --release
      - name: Test Rust project
        run: cargo test --release --workspace
