[package]
name = "web-router"
edition = "2021"
version.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
web.workspace = true

axum.workspace = true
